# Generated by Django 2.0.13 on 2019-07-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=14)),
                ('responsavel', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('solucao', models.CharField(max_length=100)),
            ],
        ),
    ]
